version: '3.5'
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres/apollo -schemas=blog -user=user -password=changeme -baselineOnMigrate=true -connectRetries=60 migrate
    volumes:
      - ./docker/flyway/migrations:/flyway/sql
    depends_on:
      - postgres
    networks: 
      - apollo-tsed-network   

  postgres:
    image: postgres:11
    container_name: postgres_container_apollo_tsed
    environment:
      POSTGRES_DB: apollo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
      - apollo-tsed-volume:/data/postgres
    ports:
      - 5432:5432
    networks:
      - apollo-tsed-network
    restart: unless-stopped

networks:
  apollo-tsed-network:
    driver: bridge
    
volumes:
  apollo-tsed-volume: